<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * DecisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecisionRepository extends EntityRepository
{
    /**
     * @param User $user
     * @param bool $id
     * @return Decision[]
     */
    public function findDecisionsForUser(User $user, $id = false)
    {
        $qb = $this->createQueryBuilder('decision')
            ->select('decision, choices, activities')
            ->leftJoin('decision.choices', 'choices')
            ->leftJoin('choices.activities', 'activities')
            ->where('decision.user = :user')
            ->setParameter('user', $user);

        if ($id) {
            $qb->andWhere('decision.id = :id')
                ->setParameter('id', $id);
        }

        return $qb->getQuery()->getResult();
    }
}
